/*
 * Copyright (C) EdgeTX
 *
 * Based on code named
 *   opentx - https://github.com/opentx/opentx
 *   th9x - http://code.google.com/p/th9x
 *   er9x - http://code.google.com/p/er9x
 *
 * License GPLv2: http://www.gnu.org/licenses/gpl-2.0.html
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 */

#include "gtests.h"

#if defined(COLORLCD) && defined(SIMU) && !GTEST_OS_WINDOWS

#include <sys/wait.h>
#include <unistd.h>

bool modelNameDialogAppliesTypedNameOnConfirmForTest();
bool modelNameDialogAppliesTypedNameOnExitForTest();
bool modelNameDialogEmptyConfirmKeepsAutoNameForTest();
bool modelNameDialogEmptyExitKeepsAutoNameForTest();
bool confirmDialogBlockingIgnoresOutsideTapForTest();
bool messageDialogIsDismissibleForTest();
bool dsDialogActionInvokesHandlerForTest();
bool confirmDialogYesIsDestructiveWhenFlaggedForTest();

// Confirming with a typed name (checkmark/OK) applies it, and the dialog
// opens with its keyboard already showing and the auto-generated name as the
// ghost/placeholder hint -- see ModelLabelsWindow::newModel.
TEST(ColorModelNameDialog, ConfirmAppliesTypedName)
{
  const pid_t pid = fork();
  ASSERT_GE(pid, 0);

  if (pid == 0) {
    alarm(2);
    _exit(modelNameDialogAppliesTypedNameOnConfirmForTest() ? 0 : 1);
  }

  int status = 0;
  ASSERT_EQ(waitpid(pid, &status, 0), pid);
  ASSERT_TRUE(WIFEXITED(status)) << "child process did not exit normally";
  EXPECT_EQ(WEXITSTATUS(status), 0);
}

// EXIT/RTN never blocks model creation (the model already exists) -- and
// must not discard a typed name either: it commits the current field
// exactly like OK, so e.g. typing "a" then pressing EXIT/RTN must not leave
// the model stuck on the auto-generated default.
TEST(ColorModelNameDialog, ExitAppliesTypedName)
{
  const pid_t pid = fork();
  ASSERT_GE(pid, 0);

  if (pid == 0) {
    alarm(2);
    _exit(modelNameDialogAppliesTypedNameOnExitForTest() ? 0 : 1);
  }

  int status = 0;
  ASSERT_EQ(waitpid(pid, &status, 0), pid);
  ASSERT_TRUE(WIFEXITED(status)) << "child process did not exit normally";
  EXPECT_EQ(WEXITSTATUS(status), 0);
}

// Confirming with an empty field must not apply a blank name.
TEST(ColorModelNameDialog, EmptyConfirmKeepsAutoGeneratedName)
{
  const pid_t pid = fork();
  ASSERT_GE(pid, 0);

  if (pid == 0) {
    alarm(2);
    _exit(modelNameDialogEmptyConfirmKeepsAutoNameForTest() ? 0 : 1);
  }

  int status = 0;
  ASSERT_EQ(waitpid(pid, &status, 0), pid);
  ASSERT_TRUE(WIFEXITED(status)) << "child process did not exit normally";
  EXPECT_EQ(WEXITSTATUS(status), 0);
}

// EXIT/RTN with nothing typed has nothing to commit -- it must degrade to
// the same outcome as an empty OK, keeping the auto-generated default.
TEST(ColorModelNameDialog, EmptyExitKeepsAutoGeneratedName)
{
  const pid_t pid = fork();
  ASSERT_GE(pid, 0);

  if (pid == 0) {
    alarm(2);
    _exit(modelNameDialogEmptyExitKeepsAutoNameForTest() ? 0 : 1);
  }

  int status = 0;
  ASSERT_EQ(waitpid(pid, &status, 0), pid);
  ASSERT_TRUE(WIFEXITED(status)) << "child process did not exit normally";
  EXPECT_EQ(WEXITSTATUS(status), 0);
}

// A confirm dialog migrated onto ds::Dialog must stay BLOCKING: an
// out-of-bounds tap neither dismisses it nor fires a handler; only an explicit
// choice / EXIT resolves it (running the cancel handler exactly once).
TEST(ColorConfirmDialog, BlockingIgnoresOutsideTap)
{
  const pid_t pid = fork();
  ASSERT_GE(pid, 0);

  if (pid == 0) {
    alarm(2);
    _exit(confirmDialogBlockingIgnoresOutsideTapForTest() ? 0 : 1);
  }

  int status = 0;
  ASSERT_EQ(waitpid(pid, &status, 0), pid);
  ASSERT_TRUE(WIFEXITED(status)) << "child process did not exit normally";
  EXPECT_EQ(WEXITSTATUS(status), 0);
}

// A message popup migrated onto ds::Dialog stays dismissible (tap-outside
// closes it), preserving POPUP_INFORMATION / POPUP_WARNING behavior.
TEST(ColorMessageDialog, StaysDismissible)
{
  const pid_t pid = fork();
  ASSERT_GE(pid, 0);

  if (pid == 0) {
    alarm(2);
    _exit(messageDialogIsDismissibleForTest() ? 0 : 1);
  }

  int status = 0;
  ASSERT_EQ(waitpid(pid, &status, 0), pid);
  ASSERT_TRUE(WIFEXITED(status)) << "child process did not exit normally";
  EXPECT_EQ(WEXITSTATUS(status), 0);
}

// The ds::Dialog action button substrate (used by the confirm YES/NO buttons)
// invokes its handler on click.
TEST(ColorDsDialog, ActionInvokesHandler)
{
  const pid_t pid = fork();
  ASSERT_GE(pid, 0);

  if (pid == 0) {
    alarm(2);
    _exit(dsDialogActionInvokesHandlerForTest() ? 0 : 1);
  }

  int status = 0;
  ASSERT_EQ(waitpid(pid, &status, 0), pid);
  ASSERT_TRUE(WIFEXITED(status)) << "child process did not exit normally";
  EXPECT_EQ(WEXITSTATUS(status), 0);
}

// A destructive confirm (delete sensor/theme, receiver reset, ...) must not
// present its irreversible YES as the visually-preferred Primary action (#8):
// `destructive=true` routes YES onto ds::ButtonRole::Destructive, and a
// confirm that does not ask for it stays Primary.
TEST(ColorConfirmDialog, YesIsDestructiveWhenFlagged)
{
  const pid_t pid = fork();
  ASSERT_GE(pid, 0);

  if (pid == 0) {
    alarm(2);
    _exit(confirmDialogYesIsDestructiveWhenFlaggedForTest() ? 0 : 1);
  }

  int status = 0;
  ASSERT_EQ(waitpid(pid, &status, 0), pid);
  ASSERT_TRUE(WIFEXITED(status)) << "child process did not exit normally";
  EXPECT_EQ(WEXITSTATUS(status), 0);
}

#endif
