/*
 * Copyright (C) EdgeTX
 *
 * Based on code named
 *   opentx - https://github.com/opentx/opentx
 *   th9x - http://code.google.com/p/th9x
 *   er9x - http://code.google.com/p/er9x
 *
 * License GPLv2: http://www.gnu.org/licenses/gpl-2.0.html
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 */

#include "gtests.h"

#if defined(COLORLCD) && defined(SIMU) && !GTEST_OS_WINDOWS

#include <sys/wait.h>
#include <unistd.h>

bool modelNameDialogAppliesTypedNameOnConfirmForTest();
bool modelNameDialogKeepsAutoNameOnExitForTest();
bool modelNameDialogEmptyConfirmKeepsAutoNameForTest();

// Confirming with a typed name (checkmark/OK) applies it, and the dialog
// opens with its keyboard already showing and the auto-generated name as the
// ghost/placeholder hint -- see ModelLabelsWindow::newModel.
TEST(ColorModelNameDialog, ConfirmAppliesTypedName)
{
  const pid_t pid = fork();
  ASSERT_GE(pid, 0);

  if (pid == 0) {
    alarm(2);
    _exit(modelNameDialogAppliesTypedNameOnConfirmForTest() ? 0 : 1);
  }

  int status = 0;
  ASSERT_EQ(waitpid(pid, &status, 0), pid);
  ASSERT_TRUE(WIFEXITED(status)) << "child process did not exit normally";
  EXPECT_EQ(WEXITSTATUS(status), 0);
}

// EXIT/cancel never blocks model creation and never applies a partially
// typed name -- the caller keeps whatever name creation already produced.
TEST(ColorModelNameDialog, ExitKeepsAutoGeneratedName)
{
  const pid_t pid = fork();
  ASSERT_GE(pid, 0);

  if (pid == 0) {
    alarm(2);
    _exit(modelNameDialogKeepsAutoNameOnExitForTest() ? 0 : 1);
  }

  int status = 0;
  ASSERT_EQ(waitpid(pid, &status, 0), pid);
  ASSERT_TRUE(WIFEXITED(status)) << "child process did not exit normally";
  EXPECT_EQ(WEXITSTATUS(status), 0);
}

// Confirming with an empty field must not apply a blank name.
TEST(ColorModelNameDialog, EmptyConfirmKeepsAutoGeneratedName)
{
  const pid_t pid = fork();
  ASSERT_GE(pid, 0);

  if (pid == 0) {
    alarm(2);
    _exit(modelNameDialogEmptyConfirmKeepsAutoNameForTest() ? 0 : 1);
  }

  int status = 0;
  ASSERT_EQ(waitpid(pid, &status, 0), pid);
  ASSERT_TRUE(WIFEXITED(status)) << "child process did not exit normally";
  EXPECT_EQ(WEXITSTATUS(status), 0);
}

#endif
